version: '3.3'
services:
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - pma_arbitrary=1
      - pma_host=db
    depends_on:
      - db
    ports:
      - 8080:80
  wordpress:
    build: ./wordpress
    image: wordpress
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp
    depends_on:
      - db
    volumes:
      - ../fs:/var/www/html
    ports:
      - 80:80
